name: Retrieve Secret


runs:
  using: 'composite'
  steps:
      - shell: bash
        run: |
          echo "This is python command line "
          python3 -c "print('hello world')"
          python3 set_env.py
